=== redirect2me/resolvers/data/resolver.schema.json
{
  "$id": "http://resolve.rs/data/resolver.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {},
  "properties": {
    "company": {
      "$id": "#/properties/company",
      "default": "",
      "examples": [
        "Example Ltd"
      ],
      "title": "Company Name",
      "type": "string"
    },
    "config": {
      "$id": "#/properties/config",
      "minProperties": 1,
      "patternProperties": {
        "^([a-z]+)$": {
          "$id": "#/properties/config/properties",
          "properties": {
            "doh": {
              "$id": "#/properties/config/properties/doh",
              "items": {
                "$id": "#/properties/config/properties/doh/items",
                "default": "",
                "examples": [
                  "https://doh.example.com/doh"
                ],
                "pattern": "^(.*)$",
                "title": "URLs for DoH servers",
                "type": "string"
              },
              "title": "DoH server URL list",
              "type": "array"
            },
            "ipv4": {
              "$id": "#/properties/config/properties/ipv4",
              "items": {
                "$id": "#/properties/config/properties/ipv4/items",
                "default": "",
                "examples": [
                  "192.168.1.10",
                  "192.168.1.11"
                ],
                "pattern": "^(.*)$",
                "title": "IPv4 addresses",
                "type": "string"
              },
              "title": "List of IPv4 Addresses",
              "type": "array"
            },
            "ipv6": {
              "$id": "#/properties/config/properties/ipv6",
              "items": {
                "$id": "#/properties/config/properties/ipv6/items",
                "default": "",
                "examples": [
                  "2a0d:2a00:1::1",
                  "2a0d:2a00:2::1"
                ],
                "pattern": "^(.*)$",
                "title": "IPv6 address",
                "type": "string"
              },
              "title": "List of IPv6 addresses",
              "type": "array"
            }
          },
          "required": [
            "ipv4"
          ],
          "title": "A configuration",
          "type": "object"
        }
      },
      "title": "List of configurations",
      "type": "object"
    },
    "details": {
      "$id": "#/properties/details",
      "default": "",
      "examples": [
        "LATER"
      ],
      "pattern": "^(.*)$",
      "title": "The Details Schema",
      "type": "string"
    },
    "draft": {
      "$id": "#/properties/draft",
      "default": false,
      "examples": [
        false
      ],
      "title": "Hide this resolver on the public website",
      "type": "boolean"
    },
    "icon": {
      "$id": "#/properties/icon",
      "default": "",
      "examples": [
        "https://www.vectorlogo.zone/logos/example/example-icon.svg"
      ],
      "pattern": "^(.*)$",
      "title": "The Icon Schema",
      "type": "string"
    },
    "location": {
      "$id": "#/properties/location",
      "default": "",
      "examples": [
        "unknown"
      ],
      "pattern": "^(.*)$",
      "title": "Country code of this resolver's headquarters",
      "type": "string"
    },
    "logo": {
      "$id": "#/properties/logo",
      "default": "",
      "examples": [
        "https://www.vectorlogo.zone/logos/example/example-ar21.svg"
      ],
      "pattern": "^(.*)$",
      "title": "SVG logo (2:1 aspect ratio, must include company name)",
      "type": "string"
    },
    "name": {
      "$id": "#/properties/name",
      "default": "",
      "examples": [
        "Example Public DNS"
      ],
      "pattern": "^(.*)$",
      "title": "Resolver's name.  Often (but not always) the same as the company name",
      "type": "string"
    },
    "social": {
      "$id": "#/properties/social",
      "properties": {
        "twitter": {
          "$id": "#/properties/social/properties/twitter",
          "default": "",
          "examples": [
            "https://twitter.com/cleanbrowsing"
          ],
          "pattern": "^(.*)$",
          "title": "Twitter handle",
          "type": "string"
        }
      },
      "title": "Social media links",
      "type": "object"
    },
    "tags": {
      "$id": "#/properties/tags",
      "items": {
        "$id": "#/properties/tags/items",
        "default": "",
        "examples": [
          "malware",
          "family",
          "freemium"
        ],
        "pattern": "^(.*)$",
        "title": "The Items Schema",
        "type": "string"
      },
      "title": "Tags",
      "type": "array"
    },
    "url": {
      "$id": "#/properties/url",
      "default": "",
      "examples": [
        "https://cleanbrowsing.org/"
      ],
      "pattern": "^(.*)$",
      "title": "The Url Schema",
      "type": "string"
    }
  },
  "required": [
    "company",
    "config",
    "icon",
    "location",
    "logo",
    "name",
    "url"
  ],
  "title": "Resolver",
  "type": "object"
}

=== redirect2me/resolvers/data/resolvers/freenomworld.json
{
  "company": "Freenom",
  "config": {
    "default": {
      "ipv4": [
        "80.80.80.80",
        "80.80.81.81"
      ]
    }
  },
  "icon": "https://www.vectorlogo.zone/logos/freenomworld/freenomworld-icon.svg",
  "location": "nl",
  "logo": "https://www.vectorlogo.zone/logos/freenomworld/freenomworld-ar21.svg",
  "name": "Freenom World",
  "tags": [],
  "url": "http://www.freenom.world/en/index.html?lang=en"
}

=== redirect2me/resolvers/data/resolvers/comodo.json
{
  "company": "Comodo",
  "config": {
    "default": {
      "ipv4": [
        "8.26.56.26",
        "8.20.247.20"
      ]
    }
  },
  "icon": "https://www.vectorlogo.zone/logos/comodo/comodo-icon.svg",
  "location": "us",
  "logo": "https://www.vectorlogo.zone/logos/comodo/comodo-ar21.svg",
  "name": "Comodo Secure DNS",
  "tags": [],
  "url": "https://www.comodo.com/secure-dns/"
}

=== redirect2me/resolvers/data/resolvers/dnswatch.json
{
  "company": "DNS.WATCH",
  "config": {
    "default": {
      "ipv4": [
        "84.200.69.80",
        "84.200.70.40"
      ],
      "ipv6": [
        "2001:1608:10:25::1c04:b12f",
        "2001:1608:10:25::9249:d69b"
      ]
    }
  },
  "icon": "https://www.vectorlogo.zone/logos/dnswatch/dnswatch-icon.svg",
  "location": "de",
  "logo": "https://www.vectorlogo.zone/logos/dnswatch/dnswatch-ar21.svg",
  "name": "DNS.WATCH",
  "tags": [],
  "url": "https://dns.watch/index"
}

=== redirect2me/resolvers/data/resolvers/dnsreactor.json
{
  "company": "VPNReactor",
  "config": {
    "default": {
      "ipv4": [
        "104.236.210.29",
        "45.55.155.25"
      ]
    }
  },
  "draft": true,
  "icon": "https://www.vectorlogo.zone/logos/vpnreactor/vpnreactor-icon.svg",
  "location": "us",
  "logo": "https://www.vectorlogo.zone/logos/vpnreactor/vpnreactor-ar21.svg",
  "name": "DNSReactor",
  "tags": [],
  "url": "http://dnsreactor.net/"
}
